name: Laravel with Composer and Vite.js

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: ladybugpizza
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Thay bằng phiên bản PHP bạn đang sử dụng

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-scripts --no-dev

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x' # Thay bằng phiên bản Node.js bạn sử dụng

    - name: Cache npm packages
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install npm dependencies
      run: npm install

    - name: Build assets with Vite
      run: npm run build

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate Laravel key
      run: php artisan key:generate

    # Chạy migration database và seed
    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h127.0.0.1 --silent; do
          sleep 1
        done

    - name: Run database migrations and seed
      run: php artisan migrate:fresh --seed
